ModelTranslationFrom
zostera/django-modeltrans pull request #67
Opened 2021-05-28 17:36 UTC by danielvdp

This PR adds ModelTranslationForm to the ModelTrans package.

2021-05-28 17:38 UTC, danielvdp commented on tests/app/settings.py
> +        "PASSWORD": "Ploei888",
```suggestion
        "USER": "modeltrans",
        "PASSWORD": "modeltrans",
```

2021-06-10 17:08 UTC, danielvdp commented on modeltrans/forms.py
> +                        if opts.fields and original_field_name in base_fields and field_name not in base_fields:
ik loop hier vast @jieter - black wil hier meerdere regels van maken, en flake8 wil dat niet. Ik krijg het niet voor elkaar om ze beiden tevreden te houden. Heb al geprobeert om de versies te veranderen.

2021-06-10 17:28 UTC, jieter requested changes
Voor flake8 van black, heb je de config vergeleken met die in obs?

2021-06-10 17:28 UTC, jieter commented on docs/pages/translationmodelform.rst
> +            fields = (name, text)
```suggestion
            fields = ("name", "text")
```

2021-06-10 17:28 UTC, jieter commented on docs/pages/translationmodelform.rst
> +This will define a form with maximally three language entries per field, say 'nl', 'fr' and 'en', where 'nl' is the
```suggestion
This will define a form with at most three inputs per field, say 'nl', 'fr' and 'en', where 'nl' is the
```

2021-06-10 17:28 UTC, jieter commented on docs/pages/translationmodelform.rst
> +fields are in the form, where the form field_order parameter can be used to define the field ordering.
Please use semantic line breaks: https://sembr.org/

2021-06-10 17:28 UTC, jieter commented on docs/pages/translationmodelform.rst
> +    - Overlap is removed, e.g. ["browser", "fr", "fallback"], becomes ["fr"] if all are equal.
```suggestion
    - Overlap is removed, e.g. ["browser", "fr", "fallback"], becomes ["fr"] if browser language and fallback are also "fr".
```

2021-06-10 17:28 UTC, jieter commented on docs/pages/translationmodelform.rst
> +     where translation_language_string is defined in Meta options as, e.g.: translation_language_string = _("translatable language")
- Please use backticks around code fragments and argument names used in prose.
- 'Future' is not something I would include in the documentation.

2021-06-10 17:28 UTC, jieter commented on tests/app/models.py
> +    )
```suggestion
    i18n = TranslationField(fields=("title", "header"), fallback_language_field="default_language")
```

2021-06-10 17:28 UTC, jieter commented on tests/test_forms.py
> +        ]  # adding start_date to test the ordering
```suggestion
        fields = ["title", "start_date", "default_language", "header"]
```

2021-06-10 17:28 UTC, jieter commented on tests/test_forms.py
> +            ValueError, "included_languages: option es_it is not permitted"
Isn't it better to replace 'option' with 'value' here?

2021-06-10 17:28 UTC, jieter commented on tests/test_forms.py
> +            ],
Does this fit on one line?

2021-06-10 17:28 UTC, jieter commented on tests/test_forms.py
> +            title_field = form.fields["title"]
```suggestion
            title_field = Form().fields["title"]
```

2021-06-10 17:28 UTC, jieter commented on tests/test_forms.py
> +        challenge = Challenge.objects.create(title="english", title_fr="espanol")
Why create a non-persistent model insantance on row 262, and then shadow it with a persisted instance?

2021-06-10 17:28 UTC, jieter commented on modeltrans/forms.py
> +        )  # include all possible languages for the site
```suggestion
        included_languages = get_available_languages()
```

2021-06-10 17:28 UTC, jieter commented on modeltrans/forms.py
> +        self.form_i18n_fields = self.form_i18n_fields()
```suggestion
        self.form_i18n_fields = [field for field in self.model_i18n_field.fields if field in self.base_fields.keys()]
```

Do we need the `form_`-prefix here?

2021-06-10 17:28 UTC, jieter commented on modeltrans/forms.py
> +
```suggestion
```

2021-06-10 17:28 UTC, jieter commented on modeltrans/forms.py
> +            # the order of languages and fields of that language should be the same
'should' sound a bit scary. Can you query the language from the field? That would simplify this a bit.

2021-06-10 17:28 UTC, jieter commented on modeltrans/forms.py
> +                ].label = f"{original_field.label} ({language.upper()}, {label_text})"
```suggestion
                label = f"{original_field.label} ({language.upper()}, {label_text})"
                self.fields[field_name].label = label
```

2021-06-10 17:28 UTC, jieter commented on modeltrans/forms.py
> +                translation = language != self.fallback_language
I think naming this `is_translation` improves readability.

2021-06-10 19:14 UTC, danielvdp commented on modeltrans/forms.py
> +            # the order of languages and fields of that language should be the same
Do you prefer this way?

2021-06-10 19:16 UTC, danielvdp commented on tests/test_forms.py
> +            ],
black is not allowing it

2021-06-10 19:27 UTC, jieter commented on modeltrans/forms.py
> +            # the order of languages and fields of that language should be the same
If you can avoid constructions needing comments mentioning you are not sure it works I prefer them, yes.

2021-06-10 19:27 UTC, jieter commented on tests/test_forms.py
> +            ],
Jammer dan

2021-06-21 14:03 UTC, jieter reviewed
Hier weer wat gedachten. Ik wil ook nog graag door de test-cases heen lopen, maar dat lukt vandaag niet meer.

2021-06-21 14:03 UTC, jieter commented on docs/pages/translationmodelform.rst
> +This will define a form with at most three inputs per field, say 'nl', 'fr' and 'en',
```suggestion
This defines a form with at most three language inputs per field, say 'nl', 'fr' and 'en',
```

2021-06-21 14:03 UTC, jieter commented on docs/pages/translationmodelform.rst
> +        i18n = TranslationField(fields=("name",), fallback_language_field="default_language")
```suggestion
        i18n = TranslationField(fields=("name", "text"), fallback_language_field="default_language")
```
?

2021-06-21 14:03 UTC, jieter commented on docs/pages/translationmodelform.rst
> +------------------
```suggestion
`included_languages`
--------------------
```

2021-06-21 14:03 UTC, jieter commented on docs/pages/translationmodelform.rst
> +        - "fallback": the fallback language either define in the form, the model instance, or in the system, in that order of priority
```suggestion
        - `"browser"`: the language that is active in the browser session
        - `"fallback"`: the fallback language either defined in the form, the model instance, or in the system, in that order of priority
```

2021-06-21 14:03 UTC, jieter commented on docs/pages/translationmodelform.rst
> +    - Overlap is removed, e.g. `["browser", "fr", "fallback"]`, becomes `["fr"]` if browser language and fallback are also "fr".
```suggestion
    - Duplicate languages are removed, e.g. `["browser", "fr", "fallback"]`, becomes `["fr"]` if browser language and fallback are also `"fr"`.
```

2021-06-21 14:03 UTC, jieter commented on docs/pages/translationmodelform.rst
> +        - a language code: e.g. "fr", "it"
```suggestion
        - a language code: e.g. `"fr"`, `"it"`
```

2021-06-21 14:03 UTC, jieter commented on docs/pages/translationmodelform.rst
> +Included_languages can be defined in the form Meta options as in the example above, or as a form kwarg as in::
```suggestion
The value of `included_languages` can be defined in the form `Meta` options as in the example above, or as a form `kwarg` as in::
```

Is het niet beter om deze optie `include_languages` te noemen: gebiedede wijs ipv verleden tijd? Of waarom niet simpelweg `languages`?

2021-06-21 14:03 UTC, jieter commented on docs/pages/translationmodelform.rst
> +
```suggestion
`fallback_language`
-------------------

```

Deze en verderop in dit kopje nog een aantal code-fragmenten die van backticks voorzien mogen worden.

2021-06-21 14:03 UTC, jieter commented on modeltrans/forms.py
> +# setting fallback to readonly
Ik wil de TODO's graag buiten de changeset houden die we gaan mergen. Dus als we het niet oplossen: wil je dan de TODO verplaatsen een issue op deze repo?

2021-06-21 14:03 UTC, jieter commented on modeltrans/forms.py
> +            # based on ModelForm
```suggestion
            # Override base_fields with properly determined set of all translation fields based on ModelForm
```

2021-06-21 14:03 UTC, jieter commented on modeltrans/forms.py
> +    ModelForm that adds fields for translations.
Volgens mij is de 'feature' van deze form juist dat het niet teveel toevoegt, standaard krijg je voor elke taal een input, wat nogal lange forms oplevert.

De docstring lijkt vrij veel duplicatie met de tekst in `docs/`. Wellicht beter om te verwijzen?

2021-06-21 14:03 UTC, jieter commented on modeltrans/forms.py
> +        # NOTE: because we update opts.fields and opts.exclude in META, field initial values are set in ModelForm
```suggestion
        # Because we update opts.fields and opts.exclude in Meta, field initial values are set in ModelForm
```

`Meta`? Of bedoel je `TranslationModelFormMetaClass`?

2021-06-21 14:03 UTC, jieter commented on modeltrans/forms.py
> +            # list is created in order of languages
```suggestion
```
Lijkt me niet veel toevoegen?

2021-06-21 14:03 UTC, jieter commented on modeltrans/forms.py
> +        return field_dict
Waarom niet simpelweg `fields`?

2021-06-21 14:03 UTC, jieter commented on modeltrans/forms.py
> +    def set_included_field_properties(self):
is `included` niet een beetje vreemde term in deze methode? Is `set_translation_field_properties` niet beter?

En `properties`, zou dat niet `attributes` moeten zijn?

2021-06-21 14:03 UTC, jieter commented on modeltrans/forms.py
> +        self.included_fields = self.included_fields()
Dit werkt, maar is wel potentieel verwarrend: de inhoud van het attribuut komt uit een functie met dezelfde naam. Ik zou iets als dit verwachten:
```suggestion
        self.included_fields = self.get_included_fields()
```

2021-06-21 14:03 UTC, jieter commented on modeltrans/forms.py
> +        # form parameter field_order takes priority, otherwise adopt order of fields in meta fields option, if available
```suggestion
        # Form parameter field_order takes priority, otherwise adopt order of fields in Meta fields option, if available
```

2021-06-21 14:03 UTC, jieter commented on modeltrans/forms.py
> +        For the Meta 'excludes' option we do a cruder ordering where translated fields types are grouped,
```suggestion
        For the Meta.excludes use a cruder ordering where translated fields types are grouped,
```

2021-06-21 14:03 UTC, jieter commented on modeltrans/forms.py
> +        but the per type the languages are in order of: browser, other, fallback
deze zin loopt wat wonderlijk, start je een nieuwe zin bij 'languages'?

2021-06-21 14:03 UTC, jieter commented on modeltrans/forms.py
> +                self.fields.pop(field_name)
Is dit niet duidelijker in 1 pass?

2021-06-21 14:03 UTC, jieter commented on modeltrans/forms.py
> +        return get_default_language()  # TODO: should be use get_fallback_chain? based on language?
Dat zou ik voorlopig nog even niet doen: dat zou inhouden dat je alle velden uit de fallback chain moet opnemen, wat er potientieel meer zijn dan je nu uitlegt.

2021-06-21 14:03 UTC, jieter commented on tests/test_forms.py
> +        widgets = {"title": forms.widgets.Textarea}  # add widget to test field setting
Deze comment voegt voor mij niet veel toe, de test die dit aspect gebruikt zou duidelijk genoeg moeten zijn.

2021-06-21 14:24 UTC, danielvdp commented on docs/pages/translationmodelform.rst
> +you can used TranslationModelForm to specify which translation fields to include and for which languages.
```suggestion
you can use TranslationModelForm to specify which translation fields to include and for which languages.
```

2021-06-21 14:26 UTC, danielvdp commented on docs/pages/translationmodelform.rst
> +Requires "fallback" to be included in included_languages.
```suggestion
Requires `"fallback"` to be included in `included_languages`.
```

2021-06-21 14:27 UTC, danielvdp commented on docs/pages/translationmodelform.rst
> +Can be defined via the form Meta options as in the example above, and also be passed as a Kwarg like included_languages.
```suggestion
Can be defined via the form `Meta` options as in the example above, and also be passed as a kwarg like `included_languages`.
```

2021-06-21 14:27 UTC, danielvdp commented on docs/pages/translationmodelform.rst
> +    2) the Meta option "fallback_language":
```suggestion
    2) the `Meta` option `"fallback_language"`:
```

2021-06-21 14:28 UTC, danielvdp commented on docs/pages/translationmodelform.rst
> +        e.g. Meta: fallback_language = "fr"
```suggestion
        e.g. `Meta`: `fallback_language = "fr"`
```

2021-06-21 14:28 UTC, danielvdp commented on docs/pages/translationmodelform.rst
> +    4) The default language of the system: If no `Meta` option is given fallback reverts to `get_default_language()`
```suggestion
    3) a custom fallback of a model instance set via `"fallback_language_field"`:
        e.g. `i18n = TranslationField(fields=("title", "header"), fallback_language_field="language_code")`
    4) The default language of the system: If no `Meta` option is given fallback reverts to `get_default_language()`
```

2021-06-21 14:30 UTC, danielvdp commented on modeltrans/forms.py
> +    ModelForm that adds fields for translations.
"Model form that only adds translation fields for specified languages." zoeits beter?

2021-06-21 14:33 UTC, danielvdp commented on modeltrans/forms.py
> +        # NOTE: because we update opts.fields and opts.exclude in META, field initial values are set in ModelForm
Eigenlijk bedoel ik: Given that we set opt.fields and opts.exclude in Meta, the setting of initial values that occurs in ModelForm includes any additional translation fields that have been added in Meta.

2021-06-21 14:35 UTC, danielvdp commented on modeltrans/forms.py
> +                self.fields.pop(field_name)
Je bedoelt de excluded fields loop en de pop loop samen voegen?

2021-06-21 14:36 UTC, danielvdp commented on modeltrans/forms.py
> +        return get_default_language()  # TODO: should be use get_fallback_chain? based on language?
Okay

2021-06-21 14:36 UTC, danielvdp commented on modeltrans/forms.py
> +        return get_default_language()  # TODO: should be use get_fallback_chain? based on language?
```suggestion
        return get_default_language()
```

2021-06-21 14:36 UTC, danielvdp commented on tests/test_forms.py
> +        widgets = {"title": forms.widgets.Textarea}  # add widget to test field setting
```suggestion
        widgets = {"title": forms.widgets.Textarea}
```

2021-06-21 15:37 UTC, danielvdp commented on docs/pages/translationmodelform.rst
> +Included_languages can be defined in the form Meta options as in the example above, or as a form kwarg as in::
languages van gemaakt, en self.languages in de form language_codes genoemt

2021-06-21 16:33 UTC, danielvdp commented on modeltrans/forms.py
> +        languages = get_available_languages()
is "get_available_languages" hoe modeltrans het normaal doet? Dus dan is dit okee toch?

2021-06-21 16:33 UTC, danielvdp commented on modeltrans/forms.py
> +            # TODO FUTURE - "all": all system languages are included
```suggestion
```

2021-06-21 16:36 UTC, danielvdp commented on modeltrans/forms.py
> +                # TODO FUTURE later fallback_readonly = False
```suggestion
```

2021-06-21 16:36 UTC, danielvdp commented on modeltrans/forms.py
> +            #    raise ValueError("included languages: you cannot include other options when including 'all'")
```suggestion
```

2021-06-21 16:37 UTC, danielvdp commented on modeltrans/forms.py
> +                #    languages = get_available_languages()
```suggestion
```

2021-06-21 16:38 UTC, danielvdp commented on modeltrans/forms.py
> +                # TODO: need to consider what to do with en_GB style languages ...?
This seems still an issue

2021-06-21 16:38 UTC, danielvdp commented on modeltrans/forms.py
> +                    )  # assuming above checks assure this is an existing language in the system
```suggestion
                    ) 
```

2021-06-21 17:25 UTC, danielvdp commented
Some tests failing that were not failing bofore ... not sure why yet.

2021-06-22 08:11 UTC, jieter requested changes
Another batch of feedback.

2021-06-22 08:11 UTC, jieter commented on CHANGELOG.md
> + - Add TranslationModelForm
```suggestion
 - Add `TranslationModelForm`
```

2021-06-22 08:11 UTC, jieter commented on docs/pages/translationmodelform.rst
> +you can use TranslationModelForm to specify which translation fields to include and for which languages.
```suggestion
`TranslationModelForm`
======================

`TranslationModelForm` is an adaptation of Django's `django.forms.ModelForm` that allow management of translation fields.
Assuming your model is translated with modeltrans,
you can use `TranslationModelForm` to specify which languages to includes form fields for.
```

2021-06-22 08:11 UTC, jieter commented on docs/pages/translationmodelform.rst
> +For example, given a NewsRoom model::
```suggestion
For example, given a `NewsRoom` model::
```

2021-06-22 08:11 UTC, jieter commented on docs/pages/translationmodelform.rst
> +You can define a TranslationModelForm as::
```suggestion
You can define a form using `TranslationModelForm` as::
```

2021-06-22 08:11 UTC, jieter commented on docs/pages/translationmodelform.rst
> +where the form field_order parameter can be used to define the field ordering.
```suggestion
This defines a form with at most three language inputs per field, say `"nl"`, `"fr"` and `"en"`,
where `"nl"` is the active browser language, and `"en"` the defined fallback language.
`Meta.exclude` can also be used to define which fields are in the form,
where the forms' `field_order` parameter can be used to define the field ordering.
```

2021-06-22 08:11 UTC, jieter commented on docs/pages/translationmodelform.rst
> +-------------------
```suggestion
`languages`
-----------
```

2021-06-22 08:11 UTC, jieter commented on docs/pages/translationmodelform.rst
> +        - a language code: e.g. `"fr"`, `"it"`
```suggestion
        - any language code: e.g. `"fr"`, `"it"`
```

2021-06-22 08:11 UTC, jieter commented on docs/pages/translationmodelform.rst
> +languages can be defined in the form Meta options as in the example above, or as a form kwarg as in::
```suggestion
`languages` can be defined in the form `Meta` options as in the example above, or as a form kwarg as in::
```

2021-06-22 08:11 UTC, jieter commented on docs/pages/translationmodelform.rst
> +Defines the fallback_language in the form.
```suggestion
Defines the fallback language for this form.
```

2021-06-22 08:11 UTC, jieter commented on docs/pages/translationmodelform.rst
> +    1) fallback_language passed as form parameter:
```suggestion
    1) `fallback_language` passed as form parameter:
```

2021-06-22 08:11 UTC, jieter commented on docs/pages/translationmodelform.rst
> +    2) the `Meta` option `"fallback_language"`:
```suggestion
    2) the `Meta` option `fallback_language`:
```

2021-06-22 08:11 UTC, jieter commented on docs/pages/translationmodelform.rst
> +        e.g. `Meta`: `fallback_language = "fr"`
```suggestion
        e.g. `class Meta: fallback_language = "fr"`
```

2021-06-22 08:11 UTC, jieter commented on docs/pages/translationmodelform.rst
> +    3) a custom fallback of a model instance set via `"fallback_language_field"`:
```suggestion
    3) A custom fallback of a model instance set via `fallback_language_field`:
```

2021-06-22 08:11 UTC, jieter commented on docs/pages/translationmodelform.rst
> +field properties
```suggestion
Field properties
```

2021-06-22 08:11 UTC, jieter commented on docs/pages/translationmodelform.rst
> +
```suggestion
```

2021-06-22 08:11 UTC, jieter commented on modeltrans/forms.py
> +                # TODO: need to consider what to do with en_GB style languages ...?
Yes, I think we support language variants, so assuming `len(language) == 2` is a valid language is not good.

You already use `get_available_languages()`, so this check could be simplified to something like:

```python
if value not in get_available_languages() and value not in LANGUAGE_OPTIONS:
    raise ValueError(f"languages: value {value} is not permitted")
```

I'm not sure what's the benefit of defining `LANGUAGE_OPTIONS` and then using plain strings "browser" and "fallback". Iterating on that, what about:


```python
valid_languages = get_available_languages()
for value in self.languages:
    if value == "browser":
       value = get_language()
    elif value == "fallback":
        value = self.fallback_language
    if value not in valid_languages:
        raise ValueError(f"languages: value {value} is not permitted")
    languages.append(value)
```

2021-06-22 08:11 UTC, jieter commented on modeltrans/forms.py
> +            raise ValueError("languages: Error. No languages have been defined.")
Error is implied by the exception type?

```suggestion
            raise ValueError("languages: No languages have been defined.")
```

2021-06-22 08:11 UTC, jieter commented on tests/test_forms.py
> +    field_order = ["start_date", "title", "end_date"]  # test the custom field_order setting
~why is field_order a class attribute and not a class Meta attribute?~

I see this is Django's `Form.field_order`
https://docs.djangoproject.com/en/3.2/ref/forms/api/#django.forms.Form.field_order

2021-06-22 08:11 UTC, jieter commented on tests/test_forms.py
> +            Form(languages=["xx", "fallback"])
After the code producing this error is simplified, this could be simplified too:

```suggestion
        for language in [0, "es_it", "e", "xx"]:
            with self.assertRaisesMessage(ValueError, f"languages: {language} is not permitted"):
                Form(languages=[language])
```

2021-06-22 08:11 UTC, jieter commented on tests/test_forms.py
> +            self.assertEqual(form.fallback_language, get_default_language())
Better to be explicit here:
```suggestion
            self.assertEqual(form.fallback_language, "en")
```

2021-06-22 08:11 UTC, jieter commented on tests/test_forms.py
> +
```suggestion
        challenge = Challenge.objects.create(default_language="de")
        with self.subTest("Test the fallback defined in a model instance"):
```

2021-06-22 08:11 UTC, jieter commented on tests/test_forms.py
> +            # test that the Meta option overrides the model instance
Why not this:
```suggestion
        with self.subTest("Verify the Meta option overrides the model instance"):
```

2021-06-22 08:11 UTC, jieter commented on tests/test_forms.py
> +            self.assertEqual(title_field.required, True)
Ik denk dat het goed is dat we voor `assertEqual(x, True|False)` wel `assertTrue(x)` en `assertFalse(x)` gebruiken, nu is een beetje willekeurig.
```suggestion
            self.assertTrue(title_field.required)
```

2021-06-22 14:56 UTC, danielvdp commented on docs/pages/translationmodelform.rst
> +        - a language code: e.g. `"fr"`, `"it"`
any is niet helemaal juist, alleen die gedefineerd zijn in het systeem, dus:
- any system language code: e.g. ....

eens?

2021-06-22 14:57 UTC, danielvdp commented on docs/pages/translationmodelform.rst
> +Defines the fallback_language in the form.
mmm weet niet of dat beter is

2021-06-22 15:01 UTC, danielvdp commented on tests/test_forms.py
> +    field_order = ["start_date", "title", "end_date"]  # test the custom field_order setting
Did you answer your own question?

2021-06-22 15:04 UTC, danielvdp commented on docs/pages/translationmodelform.rst
> +`TranslationModelForm` is an adaptation of Django's `django.forms.ModelForm` that allow management of translation fields.
```suggestion
`TranslationModelForm` is an adaptation of Django's `django.forms.ModelForm` that allows management of translation fields.
```

2021-06-22 15:04 UTC, danielvdp commented on docs/pages/translationmodelform.rst
> +you can use `TranslationModelForm` to specify which languages to includes form fields for.
```suggestion
you can use `TranslationModelForm` to specify which languages to include form fields for.
```

2021-06-22 15:14 UTC, danielvdp commented on modeltrans/forms.py
> +                    languages.append(value)
```suggestion
valid_languages = get_available_languages()
for value in self.languages:
    if value == "browser":
       value = get_language()
    elif value == "fallback":
        value = self.fallback_language
    if value not in valid_languages:
        raise ValueError(f"languages: value {value} is not permitted")
    languages.append(value)
```

2021-06-22 15:19 UTC, danielvdp commented on modeltrans/forms.py
> +    languages.append(value)
```suggestion
        valid_languages = get_available_languages()
        languages = []
        if self.languages:
            for value in self.languages:
                if value == "browser":
                    value = get_language()
                elif value == "fallback":
                    value = self.fallback_language
                if value not in valid_languages:
                     raise ValueError(f"languages: value {value} is not permitted")
                languages.append(value)
```

2021-06-22 17:06 UTC, danielvdp commented on modeltrans/forms.py
> +                # TODO: need to consider what to do with en_GB style languages ...?
Ja veel beter

2021-06-23 06:53 UTC, jieter commented on tests/test_forms.py
> +    field_order = ["start_date", "title", "end_date"]  # test the custom field_order setting
yes!

2021-06-23 06:54 UTC, jieter commented on tox.ini
> +    psycopg2-binary>=2.8,<2.9
```suggestion
    psycopg2-binary=2.8.6
```

2021-06-23 06:55 UTC, jieter commented on tox.ini
> +    psycopg2-binary=2.8.6
```suggestion
    psycopg2-binary==2.8.6
```

2021-06-23 07:15 UTC, jieter commented
Ik heb #71 hierin gemerged, gaat nu allemaal goed.

2021-06-28 13:31 UTC, jieter commented
Ik heb lokaal de documentatie maar eens even ge`build` (met `tox -e docs`), dat ziet er zo uit:

<img width="800" alt="Screenshot 2021-06-28 at 15 23 55" src="https://user-images.githubusercontent.com/1470389/123643702-f4a7ec00-d824-11eb-87d0-7b735fd33540.png">

Ik denk dat ik `TranslationModelForm` een beetje vreemd vind staan in de index: ik zou daar meer tekst verwachten dan een class name. What about 'Translations in forms'? Ik denk dat het ook logisch is om dit boven 'advanced usage' te zetten.

Ik heb even naar de coverage report van forms.py gekeken, dit is de enige regel waar je nog wat mee kunt denk ik:

<img width="1190" alt="Screenshot 2021-06-28 at 15 30 42" src="https://user-images.githubusercontent.com/1470389/123644634-d7bfe880-d825-11eb-8c97-58d30d2bd559.png">

2021-06-28 18:32 UTC, danielvdp commented
Ik heb de docs wat mooier gemaakt + extra test toegevoegd voor de covarage van die ene regel. Ik denk overigens dat de conditie voor die regel eigenlijk nooit optreed tenzij je expliciet "title", en "title_en" in fields declareerd zoals in de nieuwe test. Maar lijkt me toch beter om het voor de zekerheid in de code te houden.

2021-06-29 06:54 UTC, jieter approved these changes
OK, I think this arrived at a good level to be merged now. Thanks for your patience adjusting things!

After merging, let's first try to integrate it by adding the zip (https://github.com/zostera/django-modeltrans/archive/refs/heads/master.zip) in `requirements.txt` and release if that raises no problems.

2021-06-29 06:55 UTC, merged

2021-06-29 13:04 UTC, danielvdp commented
🥳